on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: build and push to docker
        uses: docker/build-push-action@v1
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/prueba-github-actions:${{ github.sha }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          username: ${{ secrets.DOCKER_USERNAME }}

